version: '3.8'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php-fpm
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  php-cli:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php-cli
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
